using System;
using System.Collections.Generic;

namespace ExpressYourself.entities;
//Class automatically generated by the Entity Framework. A Partial is needed to add a Constructor
public partial class Ipaddress
{
    public int Id { get; set; }

    public int CountryId { get; set; }

    public string Ip { get; set; } = null!;

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Country Country { get; set; } = null!;
}
